name: Surprize
description: A quiz app

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.3.0+9

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_cupertino_date_picker: ^0.3.0
  add_2_calendar: ^1.2.2
  cloud_firestore: ^0.11.0+2
  firebase_auth:
  firebase_storage:
  audioplayer:
  path_provider:
  cached_network_image: ^1.1.1
  image_picker:
  image_cropper: 1.1.0
  flutter_html:
  esys_flutter_share: 1.0.2
  sqflite:
  intl:
  flutter_facebook_login: 2.0.1
  google_sign_in: 4.0.7
  firebase_messaging: 5.1.5
  flutter_local_notifications: 0.8.3
  webview_flutter: 0.3.14+1
  intro_slider: 2.2.8
  connectivity: 0.4.4
  firebase_admob: 0.9.0+6
  admob_flutter: ^0.3.3
  package_info: 0.4.0+6
  url_launcher: 5.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.0"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app-icon.png"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/app-background.png
    - assets/images/app-logo.png
    - assets/images/app-icon.png
    - assets/images/daily-quiz-challenge-text-logo.png
    - assets/images/surprize-text-logo.png
    - assets/images/surprize-text-logo-with-background.png
    - assets/user_placeholder.png
    - assets/dailyQuizPlayBackgroundMusic.mp3
    - assets/waiting_music.mp3
    - assets/image_placeholder.png
    - assets/facebook_icon.png
    - assets/instagram_icon.png
    - assets/twitter_icon.png
    - assets/winner_banner.png
    - assets/images/daily_quiz_challenge_button.png
    - assets/images/DqcPlay.jpg
    - assets/images/quiz_letter_display.jpg
    - assets/images/opening_quiz_letter.png
    - assets/images/opening_quiz_letter_two.png
    - assets/images/googlebutton.png
    - assets/images/event_help.png
    - assets/images/quick_tour.png
    - assets/images/icon1024.png

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Black.ttf
        - asset: assets/fonts/Raleway-BlackItalic.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
        - asset: assets/fonts/Raleway-BoldItalic.ttf
        - asset: assets/fonts/Raleway-Medium.ttf
        - asset: assets/fonts/Raleway-MediumItalic.ttf
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-RegularItalic.ttf
        - asset: assets/fonts/Raleway-SemiBold.ttf
        - asset: assets/fonts/Raleway-SemiBoldItalic.ttf
        - asset: assets/fonts/Raleway-Thin.ttf
        - asset: assets/fonts/Raleway-ThinItalic.ttf


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
