class StringResources{

  // App related
  static final String appTitle = "Surprize !";
  static final String appCreator = 'Silicon Guy';

  // Login page related
  static final String loginHeadingDisplay = "Enter your login information";
  static final String buttonForgotPasswordText = "Forgot password?";
  static final String buttonRegisterAccountText = "Haven't Registered? Create Account";
  static final String buttonLoginText = "Login";
  static final String loginProgressInformationDisplay = "Login in...";


  // Related to registration information Display
  static final String snackBarRegistrationSuccessMessage = "Registration Completed";
  static final String registrationProgressInformationDisplayMessage = "Saving your data...";
  static final String registrationPageCreateAccountTitleDisplay = "Create Account";
  static final String registrationPageLoginCredentialHeaderDisplay = "Setting up your information!";
  static final String referralCodeText = "Enter referral code, if any!";
  static final String referralCodeHelpText = "A referral code is a unique number provided to you "
  "if you have been referred to the app by your friend for which both parties will be rewarded with points. It can be generated by sharing app to your friends.";
  static final String buttonCreateAccountText = "Enter";
  static final String elaText = "By creating account or signing up, you agree to our";
  static final String elaTextButtonTermsAndCondition = "Terms and Conditions";
  static final String elaTextButtonPrivacyAndPolicy = "Privacy and policy";
  static final String goBackToolTipText = 'Go back';

  // Related to daily quiz challenge page
  static final String noCurrentGameText = "We are not having any quiz right now. \n Set reminder so we can let you know when next game is on!!!";
  static final String setReminderButtonText = "Set reminder";
  static final String exitButtonText = "Exit";
  static final String countDownTimeString ="Game starts at";
  static final String setReminderTitle = "Reminder for Daily Quiz Challenge";
  static final String setReminderDescription = "Let's play the daily quiz challenge!!!!";
  static final String setReminderSuccessMessage = "Reminder for daily quiz challenge has been set";
  static final String headingText = "Let's play daily quiz challenge !";
  static final String getReadyForQuizText ="Get Ready! Questions will be on your screen soon!";


}